### ISSUE TITLE
[Crash] java.lang.StackOverflowError: Exception in server tick loop

### ISSUE THREAD

**Issue by importnil** [ForestryMC/ForestryMC#1116]
http://pastebin.com/xPMprRsB
http://pastebin.com/Pq9HGv5N
http://pastebin.com/4yzKTmnC
http://pastebin.com/9viAdhwj

I got around 5-7 crashes per day, don't know their nature, and reports don't have a point for an item that crashes. Forestry is "forestry_1.7.10-4.0.10.39". Could it be that it's fixed in 4.2.10.58?

**Comment by mezz** [comment]
Thanks for the report!
I think at least some of these should be fixed in the latest version, yes. There's no reason to avoid updating, please try it out and report back if you still have any issues.

**Comment by importnil** [comment]
Thanks! Seems fixed in latest version.

**Comment by TheAndrey** [comment]
The problem is still relevant, even on the latest version.

[crash-2017-02-16_06.08.30-server.txt](https://github.com/ForestryMC/ForestryMC/files/781559/crash-2017-02-16_06.08.30-server.txt)
