### ISSUE TITLE
Blocks from the mod being replaced with other blocks from the mod on server restart.

### ISSUE THREAD

**Issue by Nurfina** [ForestryMC/ForestryMC#1543]
I have build 3 farm,s and some of the machines (carpenter and fermenter). My server is set to auto restart at the end of each day, and whenever it restarts my muiltblock farms and machione are replaces with seemingly random other blocks from the mod. This is very annoying as the second time it happened my muilblock farms where replaced with wood, which means I lost everything that was in the inventory for it as well as the blocks.

**Comment by Nedelosk** [comment]
I don't have an idea what is causing this bug .  Have you one @mezz ?

**Comment by Nurfina** [comment]
I have not yet no.

**Comment by mezz** [comment]
I don't think this bug can come from Forestry. This sounds like block ID corruption. 
Basically the save is corrupted somehow, usually by a mod crash when the world is saving. The best way to recover from this is to load a backup.

**Comment by Nurfina** [comment]
it has happened multiple times and the mod pack is an official FTB pack, Direwolf's pack. It just seems to just effect Forestry blocks. Is there and easy way for me to debug it so II can fix the conflict?

**Comment by ExDomino** [comment]
It seems that my Peat-Fire Engine in the wild (#1529) was hives before. Is there a way to edit a world to change the IDs? For example, a file stored somewhere with only a number to change? Maybe other blocks from Forestry has changed too, but as we didn't used your mod so far, we just noticed about hives.

I think I will do a backup before /stop in the future, and then always restore this backup before restart, if you say that the shutdown saving procedure is bugged.

**Comment by Irishman0816** [comment]
has anyone has success on solving this issue ?

**Comment by ExDomino** [comment]
«  Nedelosk added Not Forestry and removed Bug-major labels an hour ago »

Someone can explain to us what was the origin of this bug?

**Comment by Nedelosk** [comment]
This is not a bug. It seems like anything breaks the block IDs of forestry blocks in a world.

**Comment by OldDogy** [comment]
I'm sorry to say but no other mods get there id's shuffled around after a restart, so how is it not Forestry related ?

Note: This started happening since 1.10.2 , and is happening in every modpack that I encountered.

**Comment by ExDomino** [comment]
Even in 1.12 ? I'm in 1.12 with Forestry and this issues didn't occur on our server yet.

**Comment by OldDogy** [comment]
Just had it happen on All The Mods 3.

Tho I must admit it usually happens when the server crashes. (any unrelated crash can cause it it seems) 
Also from what i have noticed (since i have been staring at the console on each crash/restart)
the issue is boosted by people trying to logon while the server is still starting up. (might not be the case but for sure needs to be tested)

**Comment by ExDomino** [comment]
All The Mods 3 are on which version of Minecraft and on which version of Forestry?

**Comment by xenxero1** [comment]
Might be worth noting, might not, so il just throw it in here. Millenaire for some 1.7.x Version had a similar issue. Upon crash almost all of the custom blocks were replaced with blocks from other mods. 

It was a interesting logging into a world with giant houses that had Decocraft green stools for roofing.

**Comment by OldDogy** [comment]
All The Mods 3 is on:
Minecraft 1.12
Forestry: _1.12-5.4.3.137
Forge: 14.21.1.2424

**Comment by colinrgodsey** [comment]
Also seeing this issue with FTB Direwolf20 1.12 =\ On restart there's a good chance all the forestry mappings will come up different than they were before, requiring me to restore the level.dat.

**Comment by Nedelosk** [comment]
I remove some mods and now my test world has door trees and honey hives.
 ![2018-01-06_17 27 27](https://user-images.githubusercontent.com/10259214/34641629-3f8e1aac-f307-11e7-851b-13e8c2971ccc.png)
![2018-01-06_17 28 09](https://user-images.githubusercontent.com/10259214/34641630-3fa906be-f307-11e7-92f6-1f71f74789e0.png)
![2018-01-06_17 28 16](https://user-images.githubusercontent.com/10259214/34641631-3fe522e8-f307-11e7-9626-fa44a644770c.png)

**Comment by Nedelosk** [comment]
Could this happen because we don't use the register event to register the blocks ?

**Comment by andrenasturas** [comment]
I actually have the same bug on a server using FTB Revelation 1.8.0 (Minecraft 1.12, Forestry 5.8.0.256).

I'm not sure, but it does seem that the problem is due to a corruption of the saves files. We have suffered server crashes following failed backups (not enough space to save it to the server disk).

However, the bug still seems specific to Forestry : we have only seen the transformation of cherry leaves into centrifuges, and some blocks (Forestry craft table) into other random machines from Forestry (which are not usable : right clicking on a craft table transformed in a "Farm (managed)" only shuffle the player inventory, and the leaves transformed into centrifuges does nothing).

So it may be an external cause, but still, it looks like there is a specific issue with the way Forestry identifies its blocks that could be improved. The fact that so many of us reproduce very similar behavior is intriguing.

**Comment by bookerthegeek** [comment]
@andrenasturas Can you try removing [NotEnoughIDs](https://minecraft.curseforge.com/projects/notenoughids) and see if this still happens? You will need to also disable [Flat Colored Blocks](https://minecraft.curseforge.com/projects/flat-colored-blocks) and the stone variants from quark to get under the id limit.

**Comment by temp1011** [comment]
@mezz is it possible this is somehow related to https://github.com/MinecraftForge/MinecraftForge/issues/4904? Maybe something is resetting registry mappings when it shouldn't be?
EDIT: At least for the ones with crashes. The problems when removing mods is different.

**Comment by mezz** [comment]
I think it is related, almost certainly.

**Comment by temp1011** [comment]
It's quite hard to investigate corruption due to removing mods until https://github.com/MinecraftForge/MinecraftForge/pull/4856 is merged. I will see if I can write a test mod for forge to reproduce.

**Comment by mezz** [comment]
We believe this is fixed with the latest version of Forge. 🎉

**Comment by MCOfficer** [comment]
i still see this happening with forge 1.12.2, v14.23.4.2739 (forestry 1.12.2-1.5.1). had several crashes which might have been the cause for this (unfortunately the logs are no more).

**Comment by Akaitatsu** [comment]
I have been having a similar experience to what @Nedelosk shows in his screenshots. The tree "trunk" was replaced with machines and when I would shop one up, a new one would appear adjacent to where the old one was. When I chop one of the door "leaves" all the doors would fall to the ground.

This was with Forge 14.23.5.2815, Forestry 5.8.2.385, and Binnies' 2.5.1.188. The full mod list is attached.

[modlist.txt](https://github.com/ForestryMC/ForestryMC/files/2994451/modlist.txt)

**Comment by bookerthegeek** [comment]
@Akaitatsu

Remove ` NotEnoughIDs-1.5.4.3.jar` and replace it with `JustEnoughIDs` (might have that second mods name spelled wrong).

**Comment by Akaitatsu** [comment]
@bookerthegeek :
> Remove ` NotEnoughIDs-1.5.4.3.jar` and replace it with `JustEnoughIDs` (might have that second mods name spelled wrong).

Thank you! That seems to have done the trick. I've only played the updated pack for a couple days, so we'll see how it goes. No door trees or messed up world gen so far though.

**Comment by Flanngo** [comment]
Any thoughts on how to fix this if I don't have NotEnoughIDs?

I've gotten this bug a couple days ago and rebooting my server hasn't fixed it. Should I download JustEnoughIDs and try that?

**Comment by the-vindex** [comment]
Same here. Undiscovered 2 modpack, similar issues. No NotEnoughIDs.

**Comment by Silverclawthe1st** [comment]
This has been happening to me aswell but not with this mod. but every block i see besides stone is compleatly randomized like torches are orange wool for example and when i joined a server i could stand on the wool but nobody else could because, well its just a torch to them

**Comment by CroixMarlin330** [comment]
having the same issue
![Capture d'écran 2024-01-17 042747](https://github.com/ForestryMC/ForestryMC/assets/97316655/a00a2f09-d510-437c-829e-73b3377196a5)

**Comment by CroixMarlin330** [comment]
the mod i'm using is Enigmatica Experte E2E
