### ISSUE TITLE
[1.12.2] crash on startup

### ISSUE THREAD

**Issue by Aevaris** [ForestryMC/ForestryMC#2139]
I saw a few similar issues, but the crash dumps seem different than mine. Sorry if duplicate. This seems to be a forestry crash when loading using latest version (no cause-by in log besides forestry that I can tell).

[https://pastebin.com/DFYPQKNx](https://pastebin.com/DFYPQKNx)

**Comment by Aevaris** [comment]
Hmm, will need to play with this a bit more later. This may be (mostly) user error. I am semi-rebuilding my MC instance (its been awhile and new PC since last played). I reloaded my previous config files to save my past customizations. When I deleted my config folder, forestry (and everything else) loaded fine.

**Comment by temp1011** [comment]
If you enable apiculture in your old configs or disable ic2 integration it should work.

**Comment by Aevaris** [comment]
Thanks for the info. Does IC2 integration do anything outside of the bee module? I love forestry for the trees and the machines, but am not a fan of the bees. So, I usually play with apiculture = off but I do play with IC2.

**Comment by temp1011** [comment]
The IC2 plugin adds the electrical engine and generators, farming of rubber trees, some recipes and backpacks and crates. The only part that involves apiculture is trying to stop people putting bees in the recycler because that's inhumane :smile: . If you're playing with IC2  you probably want the plugin enabled.

**Comment by temp1011** [comment]
This should be fixed on the latest update.

**Comment by Aevaris** [comment]
Still crashes with 294 :(

[https://pastebin.com/P1XzqsKi](https://pastebin.com/P1XzqsKi)

**Comment by temp1011** [comment]
My bad, I missed one

**Comment by Vaygrim** [comment]
I'm getting a crash on startup using Forestry 295. I've tried the tricks mentioned above (disabled IC2 module, left apiculture enabled) and it's still happening.
[crash-2018-05-31_15.00.32-client.txt](https://github.com/ForestryMC/ForestryMC/files/2059904/crash-2018-05-31_15.00.32-client.txt)
[crash-2018-05-31_15.02.11-client.txt](https://github.com/ForestryMC/ForestryMC/files/2059905/crash-2018-05-31_15.02.11-client.txt)
[crash-2018-05-31_15.08.11-client.txt](https://github.com/ForestryMC/ForestryMC/files/2059906/crash-2018-05-31_15.08.11-client.txt)
[crash-2018-05-31_14.50.08-client.txt](https://github.com/ForestryMC/ForestryMC/files/2059907/crash-2018-05-31_14.50.08-client.txt)
[crash-2018-05-31_14.56.02-client.txt](https://github.com/ForestryMC/ForestryMC/files/2059908/crash-2018-05-31_14.56.02-client.txt)

Help? Is this relevant to the issue posted here?

**Comment by Aevaris** [comment]
Hey Vaygrim,

The issue is resolved for me in 295. If your goal is to disable bees and
you have IC2, you should disable apiculture in the modules config and
enable IC2.
