### ISSUE TITLE
Bee pollination broken?

### ISSUE THREAD

**Issue by Amelia-** [ForestryMC/ForestryMC#475]
After updating to Forestry version 3.3.0.427-unstable from 3.3.0.395-unstable there have been some very weird things happening in my world whenever I have bees working.
Mostly it's just random blocks being changed into other blocks or removed entirely. The randomness of where this happens seems very similar to how before trees would get polinated when bees were working nearby however I do have some trees nearby and they don't seem to be getting pollinated anymore at all or atleast at a very slow rate. I've seen one leaf be pollinated in the time where I have seen about 10 other blocks change.
What happens most often is stone bricks being changed to mossy stone bricks but I've also seen an apiary being turned into an apiarist chest or a buildcraft golden pipe with facade just disappear. I've seen oak wood planks being turned into spruce wood planks, weird things happen to logistics pipes like them disconnecting from other pipes or dropping their upgrades into the world.
The other day I had a buildcraft laser that was modified in some way, when I looked at it my client would crash. When I looked into the map with MCEdit the laser had :11 added to it's type or something.

When I don't have bees working none of these things happen.
Between the bees I have working are flower, jungle and rock pollination traits.

I can keep adding more things I see happening but I doubt it would help much and I'm a bit hesitant of keeping the bees at work like this because it makes quite a mess of the area around my bee hives, though the random mossy stone bricks in the stone brick buildings do add something nice to them. I have backups of the map but still, I think I'll put the bees to rest for a little while.

**Comment by Dream-Master** [comment]
Yes i have the same Problem. First i thought is it Thaumcraft (warp Effect) but i think the Bees changing the Blocks.(apiary being turned into an apiarist chest and different woods changing)
I have Extra Bees and Magic Bees installed too!

**Comment by mezz** [comment]
Thanks for the report!
That's a pretty huge problem. I'll take a look.

**Comment by marcin212** [comment]
forestry_1.7.10-3.3.0.427-unstable
I have the same problem. Butterflies do not pollinate as well.

**Comment by mezz** [comment]
Should be fixed in the latest unstable. Please take a look and let me know what you find!

**Comment by Blood-Asp** [comment]
The server i'm playing on updated to unstable#443, but Apiarys still transform into Apiarist's Chests when bees work.

**Comment by Amelia-** [comment]
I am still seeing some blocks change too when my bees are working. Things like iron chests to gold chests and I'm not entirely sure but there may have also been some stone brick to mossy stone brick changes again.
This is with unstable 439.

On the other side the trees near them do seem to be getting polinated like before.

**Comment by mezz** [comment]
I'll take another look.

**Comment by mezz** [comment]
![2015-01-30_21 10 32](https://cloud.githubusercontent.com/assets/916092/5986911/bf55a060-a8c4-11e4-9c84-a5bbf07c0eb1.png)
I was able to confirm that this is still happening in the latest unstable, with regular meadows bees.

**Comment by mezz** [comment]
Ok fixed it! I tested with the pollination rate at 1000 times normal to be sure.

**Comment by CovertJaguar** [comment]
Now I want bees that turn Stone Bricks into Mossy Stone Bricks. Are there any bees that do that?
