### ISSUE TITLE
Multifarms do not plant saplings when Arboriculture module is disabled

### ISSUE THREAD

**Issue by Angel9001** [ForestryMC/ForestryMC#830]
when useing the multi-farm it it do not plant any sapling, tryed all diffrent types
it lay down the dirt start useing feriliser and just sitt there... it has power, water, fertilizer and plenty of saplings to plant. yett nothing...

tryed with and whitout circuit board (Managed) whit copper tubes in it.. nothing happens.. allso made sure the farm land was the right size.

tryed other farm setups (crop, vegetable, etc.) and they are working just fine in the same spot i have tryed to make the treefarm.

if i plant saplings manuel it do harvest them after they grow and place wood/apples in output slot and saplings in sapling slot. there is allso dirt in the dirt slot just to make sure.

tryed both on a server and singelplayer.

**Comment by Nirek-K** [comment]
The multifarm only plants saplings on Humus, if you placed down dirt, that would be why you get the described problems. Remove dirt and allow the farm to place down humus (requires dirt in the multifarm inventory) and it should begin working.

**Comment by Angel9001** [comment]
its laying out humus, and still not planting....... its i place dirt in the machine its placeing humus... i removeing the humus when it didn't plant on that... forgot to say that maby..

edit:
I let it sit about 30 min on both humus and dirt whit no errros in the machine...

**Comment by leagris** [comment]
A bit few more questions:
- What are your Forge and Forestry versions?
- Do you use some permissions manager (there is a foresstry user that needs permissions to operate)
- Do you provide water + Forestry fertilizer (blue) + Forestry saplings (not vanilla) + dirt?
- Is your farm within a vanilla biome or some modded biome?
- Y level of farm surface?
- Is there enough energy?
- Can you replicate this with forestry alone?

**Comment by Angel9001** [comment]
Found out what the problem was

in the modules.cfg file the module 

arboriculture was set to false sins i didn't want the hole tree breeding aspect..
This disabled the farm to be able to plant trees.. turning that back to true allowed for trees to be planted. not sure if this is ment to disable a farm to be able to plant trees or not... or if i just missunderstand what that module is ment to do..

line 17:    # Adds additional tree species and products.
line 18:    B:arboriculture=false

whit this as false whit Forestry alone the farm did not plant.
tested in vanilla super flat world whit Forestry alone

the other tests where done in diffrent rwg bioms at many diffrent highs but changeing the arboriculture module to true allowed for planting in this bioms allso.

Forestry version
3.6.3.20
Forge
10.13.4.1492

**Comment by JFMillerUSA** [comment]
Not sure if it helps but I place torches around my multifarm of trees

**Comment by mezz** [comment]
@Angel9001 can you backup your world and try with the [Forestry 4.0 beta](http://minecraft.curseforge.com/mc-mods/59751-forestry/files)?

**Comment by Angel9001** [comment]
Hi there

Tryed a few diffent versions mixed and crossed back and forth

Forge:
10.13.4.1517
10.13.4.1492

Foresty
4.0.0
4.0.1
4.0.2
4.0.3
4.0.4

all came back whit crash
http://pastebin.com/YYTSw1Lt

didn't have to much time to test this time but will test some more later

**Comment by mezz** [comment]
Thanks @Angel9001, it looks like the original issue is fixed but another one came up (also because Arboriculture is disabled). I'll take a look at fixing this one soon.

**Comment by mezz** [comment]
@Angel9001 can you try out [the latest unstable build](http://jenkins.ic2.player.to/job/Forestry_Dev/)?
The crash you got should be fixed.

**Comment by Angel9001** [comment]
Downloaded tested.. fixed the crash but then it still don't plant saplings.. ;)

U can't put humus in the machine.. 
but when i put dirt in it planted a nice layer of humus on the farm land
water is full all diffrent kinds of saplings (vanilla) are in there
stack of fertilizer
plenty of power

whit arboriculture=false 
no planting
but do harvest trees if i plant them manuel

whit arboriculture=true
plants/harvest like its ment to... ;)

Allso notised that saplings planted and leafes of the tress that grew  wile the was arboriculture=true
all got deleted if u turned off indicateing that it convert the normal vanilla saplings to forestry when it plants them

Forge versions tested:
10.13.4.1492
10.13.4.1517

**Comment by mezz** [comment]
Thanks for your patience, I fixed it and tested that vanilla saplings are working this time.
