### ISSUE TITLE
The fireproof genome can not be cleared

### ISSUE THREAD

**Issue by sfchipan** [ForestryMC/ForestryMC#972]
I mate coast sequoia and apple oak that directly take from NEI. The new coast sequoia with no fireproof still grow to fireproof wood.
![1](https://cloud.githubusercontent.com/assets/4555814/11262124/5d96da78-8eb6-11e5-89d9-6790cf2bc974.jpg)
![2](https://cloud.githubusercontent.com/assets/4555814/11262127/681089ae-8eb6-11e5-9224-fe9626858430.jpg)

**Comment by mezz** [comment]
Thanks for the report!

**Comment by mezz** [comment]
Fixed in the latest version

![2015-11-19_01 33 38](https://cloud.githubusercontent.com/assets/916092/11267105/2d170a60-8e5e-11e5-8719-65a1169b4f65.png)

**Comment by sfchipan** [comment]
Thanks for fixing it! It still have a little issue inversely. The new apple oak have fireproof genome as active genome, but it grow to the wood with no fireproof.
(version 4.2.0.835)

**Comment by mezz** [comment]
Hmm that should have been fixed too. I will take a look soon.

**Comment by mezz** [comment]
Oh, there is no fireproof version of vanilla woods, so there is no fireproof oak wood.

**Comment by sfchipan** [comment]
Oh, I see.
